### ISSUE TITLE
待翻译-文章：Google Cloud TMI 系列 （ The Modernization Imperative）

### ISSUE THREAD

**Issue by node** [PECommunity/community#14]
Google Cloud TMI 系列：https://cloud.google.com/blog/topics/tmi 

- [x] [The Modernization Imperative: Shifting left is for suckers. Shift down instead]. #15 (https://cloud.google.com/blog/products/application-development/richard-seroter-on-shifting-down-vs-shifting-left)
- [x] [The Modernization Imperative: Is your platform engineering project doomed to fail?] (https://cloud.google.com/blog/products/application-modernization/alex-mcwilliam-on-how-to-avoid-platform-engineering-project-flops)  
 #17 
- [x] [The Modernization Imperative (TMI): The beauty in boring](https://cloud.google.com/blog/products/application-modernization/richard-seroter-on-the-need-to-durable-systems)   #16 

请回复文章编号来认领翻译。

步骤：

- [x] 在本地完成翻译
- [x]  fork本仓库并在article目录创建一个新文档，内容为你的翻译
- [x]  提交PR，并关联本issue
- [x]  等待review后即可合并
- [x]  发布：社区的微信公众号、网站等渠道首发；其他技术社区二次传播

**Comment by node** [comment]
认领 1

**Comment by fleeto** [comment]
认领 3

**Comment by fleeto** [comment]
认领 2

**Comment by node** [comment]
Finished.
