### ISSUE TITLE
翻译-模型：CNCF 应用交付 TAG 平台工作组 ： 平台工程成熟度模型  - 已完成

### ISSUE THREAD

**Issue by node** [PECommunity/community#22]
英文原文  https://tag-app-delivery.cncf.io/whitepapers/platform-eng-maturity-model/

翻译后可提交至CNCF 应用交付 TAG 官网   https://github.com/cncf/tag-app-delivery/

**Comment by mouuii** [comment]
hello 我刚翻译了这篇文章，怎么联系你们，有微信群吗

**Comment by node** [comment]
@mouuii 欢迎贡献。

你可选择加入 PECommunity平台工程社区，fork本仓库并在article目录里加入你的翻译内容后提交PR，社区的小伙伴会尽快review，待合并后就会在社区官网、公众号及其他技术社区等多个渠道发布。

同时，作为CNCF app delivery TAG的成员，我正在翻译官网，待上线后，即可同步发布你的翻译稿。

**Comment by node** [comment]
翻译中  [PR#502](url)

**Comment by node** [comment]
已合并提交至 CNCF app deliery TAG上游。
